//! Phase 8 Task 9/10/11 — the full required document format matrix.
//!
//! ## Evidence level: LIVE WOPI HOST + real `LibreOffice` parsing
//!
//! For each of the nine required formats this proves a genuine
//! round-trip: a real fixture is generated by real `LibreOffice`, opened
//! through the real WOPI `GetFile`, modified into a real replacement
//! document in the *same* format, saved through the real WOPI `PutFile`,
//! the session ended (`UNLOCK`), then reopened and its **content**
//! re-parsed by real `LibreOffice` to confirm the modification actually
//! landed and the file is still a valid document of its original format.
//!
//! A 200 from `PutFile` is explicitly never treated as evidence on its
//! own (Task 10) — every assertion below is against re-parsed document
//! content.
//!
//! Legacy binary formats (DOC/XLS/PPT) are genuine binary fixtures
//! produced by `LibreOffice`'s own legacy filters, never a renamed text
//! file (Task 9/11).
//!
//! Browser-driven editing is a separate, higher evidence level and is
//! not claimed here (see `PHASE8_OFFICE_EVIDENCE.md`).

use axum::http::Method;
use clouddesk_auth::{AuthPolicy, AuthService};
use clouddesk_secrets::SecretCipher;
use serde_json::{json, Value};
use sha2::{Digest, Sha256};
use sqlx::SqlitePool;
use std::net::SocketAddr;
use std::path::{Path, PathBuf};
use tokio::process::Command as TokioCommand;

// --------------------------------------------------------------
// LibreOffice fixture generation / verification
// --------------------------------------------------------------

/// Runs a headless `LibreOffice` conversion with its own dedicated
/// profile directory. `LibreOffice` single-flights on a shared user
/// profile lock, so concurrent invocations across parallel tests
/// otherwise fail each other with a bare non-zero exit.
async fn soffice_convert(outdir: &Path, filter: &str, input: &Path) -> bool {
    let profile = tempfile::tempdir().unwrap();
    TokioCommand::new("soffice")
        .arg(format!(
            "-env:UserInstallation=file://{}",
            profile.path().display()
        ))
        .args(["--headless", "--convert-to", filter, "--outdir"])
        .arg(outdir)
        .arg(input)
        .output()
        .await
        .is_ok_and(|o| o.status.success())
}

async fn soffice_available() -> bool {
    TokioCommand::new("soffice")
        .arg("--version")
        .output()
        .await
        .is_ok_and(|o| o.status.success())
}

/// What kind of document a format is, which decides both how a fixture
/// is seeded and how its content is read back.
#[derive(Clone, Copy, PartialEq, Eq)]
enum Kind {
    Text,
    Sheet,
    Slides,
}

impl Kind {
    /// The filter used to read a document's content back as inspectable
    /// text. Presentations have no text export, so they are re-parsed
    /// through flat-ODF instead — still a real `LibreOffice` parse of the
    /// saved bytes, not a ZIP peek.
    fn read_filter(self) -> &'static str {
        match self {
            Self::Text => "txt:Text",
            Self::Sheet => "csv:Text - txt - csv (StarCalc)",
            Self::Slides => "fodp",
        }
    }
}

/// Generates a real fixture of `extension` containing `marker`, by
/// seeding a source document and converting it with `LibreOffice`'s own
/// filters. Returns the fixture path.
async fn make_fixture(
    dir: &Path,
    stem: &str,
    extension: &str,
    kind: Kind,
    marker: &str,
) -> PathBuf {
    let seed = match kind {
        Kind::Text => {
            let p = dir.join(format!("{stem}-seed.txt"));
            std::fs::write(&p, format!("{marker}\n")).unwrap();
            p
        }
        Kind::Sheet => {
            let p = dir.join(format!("{stem}-seed.csv"));
            std::fs::write(&p, format!("{marker},2\n")).unwrap();
            p
        }
        Kind::Slides => {
            let p = dir.join(format!("{stem}-seed.fodp"));
            std::fs::write(&p, flat_odp(marker)).unwrap();
            p
        }
    };
    assert!(
        soffice_convert(dir, extension, &seed).await,
        "failed to generate a real .{extension} fixture"
    );
    let produced = dir.join(format!("{stem}-seed.{extension}"));
    assert!(
        produced.exists(),
        "LibreOffice did not produce {}",
        produced.display()
    );
    // Move it to a clean, stem-unique name so read-back conversions of
    // different fixtures never collide on output filenames.
    let final_path = dir.join(format!("{stem}.{extension}"));
    std::fs::rename(&produced, &final_path).unwrap();
    final_path
}

fn flat_odp(marker: &str) -> String {
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<office:document xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0"
 xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0"
 xmlns:draw="urn:oasis:names:tc:opendocument:xmlns:drawing:1.0"
 xmlns:svg="urn:oasis:names:tc:opendocument:xmlns:svg-compatible:1.0"
 office:version="1.2" office:mimetype="application/vnd.oasis.opendocument.presentation">
 <office:body><office:presentation>
  <draw:page draw:name="page1">
   <draw:frame svg:width="20cm" svg:height="3cm" svg:x="2cm" svg:y="2cm">
    <draw:text-box><text:p>{marker}</text:p></draw:text-box>
   </draw:frame>
  </draw:page>
 </office:presentation></office:body>
</office:document>"#
    )
}

/// Re-parses a saved document with real `LibreOffice` and returns its
/// readable content. This is the Task 10 verification step: it proves
/// both that the intended change is present *and* that the file is
/// still a parseable document of its own format — a corrupt save fails
/// here even if `PutFile` returned 200.
async fn read_back(path: &Path, kind: Kind) -> String {
    let outdir = tempfile::tempdir().unwrap();
    assert!(
        soffice_convert(outdir.path(), kind.read_filter(), path).await,
        "LibreOffice could not reparse {} -- the saved document is not \
         a valid file of its format",
        path.display()
    );
    let produced = std::fs::read_dir(outdir.path())
        .unwrap()
        .find_map(Result::ok)
        .unwrap_or_else(|| {
            panic!(
                "LibreOffice produced no output reparsing {}",
                path.display()
            )
        });
    let raw = std::fs::read(produced.path()).unwrap();
    String::from_utf8_lossy(&raw)
        .trim_start_matches('\u{feff}')
        .replace('\r', "")
}

// --------------------------------------------------------------
// Product harness (same shape as office_wopi_host.rs)
// --------------------------------------------------------------

async fn application() -> (String, tempfile::TempDir, SqlitePool) {
    let pool = clouddesk_db::connect("sqlite::memory:", 1).await.unwrap();
    clouddesk_db::migrate(&pool).await.unwrap();
    let auth = AuthService::new(
        pool.clone(),
        SecretCipher::new(&[37_u8; 32]).unwrap(),
        AuthPolicy::default(),
    )
    .unwrap();
    let directory = tempfile::tempdir().unwrap();
    let secret_path = directory.path().join("bootstrap.secret");
    std::fs::write(&secret_path, "format-test-secret\n").unwrap();

    let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let port = listener.local_addr().unwrap().port();
    let router =
        clouddeskd::application_router_and_media_and_library_and_runtime_and_office_configured(
            directory.path().to_owned(),
            auth,
            secret_path,
            true,
            None,
            None,
            None,
            Some(format!("http://127.0.0.1:{port}")),
        );
    tokio::spawn(async move {
        axum::serve(
            listener,
            router.into_make_service_with_connect_info::<SocketAddr>(),
        )
        .await
        .unwrap();
    });
    (format!("http://127.0.0.1:{port}"), directory, pool)
}

fn current_process_linux_identity() -> Option<clouddesk_linux::LinuxIdentity> {
    let uid = rustix::process::getuid().as_raw();
    if uid == 0 {
        return None;
    }
    clouddesk_linux::lookup_uid(uid).ok().flatten()
}

async fn http(
    base: &str,
    method: Method,
    path: &str,
    cookie: Option<&str>,
    body: Option<&Value>,
) -> reqwest::Response {
    let mut builder = reqwest::Client::new().request(
        reqwest::Method::from_bytes(method.as_str().as_bytes()).unwrap(),
        format!("{base}{path}"),
    );
    if let Some(cookie) = cookie {
        builder = builder.header(reqwest::header::COOKIE, cookie);
    }
    if let Some(body) = body {
        builder = builder
            .header(reqwest::header::CONTENT_TYPE, "application/json")
            .body(body.to_string());
    }
    builder.send().await.unwrap()
}

async fn bootstrap_admin(base: &str) -> String {
    let linux_username = current_process_linux_identity().map(|i| i.username);
    let response = http(
        base,
        Method::POST,
        "/api/v1/setup/bootstrap",
        None,
        Some(&json!({
            "secret": "format-test-secret",
            "username": "admin",
            "display_name": "Admin",
            "password": "correct horse battery staple",
            "linux_username": linux_username,
        })),
    )
    .await;
    assert_eq!(response.status(), reqwest::StatusCode::CREATED);
    login(base, "admin", "correct horse battery staple").await
}

async fn login(base: &str, username: &str, password: &str) -> String {
    let response = http(
        base,
        Method::POST,
        "/api/v1/auth/login",
        None,
        Some(&json!({"username": username, "password": password})),
    )
    .await;
    assert_eq!(response.status(), reqwest::StatusCode::OK);
    response
        .headers()
        .get(reqwest::header::SET_COOKIE)
        .unwrap()
        .to_str()
        .unwrap()
        .split(';')
        .next()
        .unwrap()
        .to_owned()
}

async fn step_up(base: &str, admin_cookie: &str) {
    let response = http(
        base,
        Method::POST,
        "/api/v1/auth/step-up",
        Some(admin_cookie),
        Some(&json!({"password": "correct horse battery staple"})),
    )
    .await;
    assert_eq!(response.status(), reqwest::StatusCode::OK);
}

async fn create_user(base: &str, admin_cookie: &str, username: &str) -> String {
    let identity = current_process_linux_identity()
        .expect("this test requires running as a real, mapped, non-root Linux user");
    step_up(base, admin_cookie).await;
    let create = http(
        base,
        Method::POST,
        "/api/v1/users",
        Some(admin_cookie),
        Some(&json!({
            "username": username,
            "display_name": username,
            "password": "user horse battery staple",
            "role_ids": ["user"],
        })),
    )
    .await;
    assert_eq!(create.status(), reqwest::StatusCode::CREATED);
    let body: Value = create.json().await.unwrap();
    let user_id = body["user_id"].as_str().unwrap().to_owned();
    let set_identity = http(
        base,
        Method::PUT,
        &format!("/api/v1/users/{user_id}/linux-identity"),
        Some(admin_cookie),
        Some(&json!({ "uid": identity.uid, "gid": identity.gid })),
    )
    .await;
    assert_eq!(set_identity.status(), reqwest::StatusCode::NO_CONTENT);
    user_id
}

async fn add_root(base: &str, admin_cookie: &str, user_id: &str, path: &Path) {
    step_up(base, admin_cookie).await;
    let response = http(
        base,
        Method::POST,
        &format!("/api/v1/users/{user_id}/assigned-roots"),
        Some(admin_cookie),
        Some(&json!({ "path": path, "access_mode": "read-write" })),
    )
    .await;
    assert_eq!(response.status(), reqwest::StatusCode::CREATED);
}

async fn mint_token(pool: &SqlitePool, user_id: &str, path: &Path) -> (String, String) {
    let canonical = std::fs::canonicalize(path).unwrap();
    let canonical = canonical.to_string_lossy().into_owned();
    let file_id = format!("f{}", unique());
    sqlx::query(
        "INSERT INTO office_wopi_files (id, canonical_path, identity_key, generation, created_at)
         VALUES (?, ?, ?, 0, 0) ON CONFLICT(identity_key) DO NOTHING",
    )
    .bind(&file_id)
    .bind(&canonical)
    .bind(&canonical)
    .execute(pool)
    .await
    .unwrap();
    let file_id: String =
        sqlx::query_scalar("SELECT id FROM office_wopi_files WHERE identity_key = ?")
            .bind(&canonical)
            .fetch_one(pool)
            .await
            .unwrap();
    let raw = format!("t{}", unique());
    let mut hasher = Sha256::new();
    hasher.update(raw.as_bytes());
    sqlx::query(
        "INSERT INTO office_wopi_tokens
            (token_hash, user_id, file_id, read_write, runtime_instance_id, created_at, expires_at)
         VALUES (?, ?, ?, 1, 'test-instance', 0, ?)",
    )
    .bind(hex::encode(hasher.finalize()))
    .bind(user_id)
    .bind(&file_id)
    .bind(
        i64::try_from(
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_secs(),
        )
        .unwrap()
            + 1800,
    )
    .execute(pool)
    .await
    .unwrap();
    (file_id, raw)
}

fn unique() -> String {
    use std::sync::atomic::{AtomicU64, Ordering};
    static COUNTER: AtomicU64 = AtomicU64::new(0);
    format!(
        "{}{}",
        std::process::id(),
        COUNTER.fetch_add(1, Ordering::Relaxed)
    )
}

// --------------------------------------------------------------
// The matrix
// --------------------------------------------------------------

/// One format's full round-trip: fixture → `GetFile` → `LOCK` → modify
/// in the same format → `PutFile` → `UNLOCK` (session end) → reopen →
/// re-parse content.
#[allow(clippy::too_many_lines)]
async fn round_trip(
    base: &str,
    pool: &SqlitePool,
    user_id: &str,
    workspace: &Path,
    extension: &str,
    kind: Kind,
) {
    let stem = format!("rt-{extension}");
    let original_marker = format!("ALPHA{}", extension.to_uppercase());
    let modified_marker = format!("OMEGA{}", extension.to_uppercase());

    let doc = make_fixture(workspace, &stem, extension, kind, &original_marker).await;
    let original_bytes = std::fs::read(&doc).unwrap();

    // Sanity: the fixture really is a valid document containing the marker.
    let before = read_back(&doc, kind).await;
    assert!(
        before.contains(&original_marker),
        ".{extension}: the generated fixture does not contain its own marker \
         (got {before:?}) -- the fixture itself is broken"
    );

    let (file_id, token) = mint_token(pool, user_id, &doc).await;
    let client = reqwest::Client::new();

    // --- open: CheckFileInfo + GetFile through the real WOPI host ---
    let info: Value = client
        .get(format!("{base}/wopi/files/{file_id}?access_token={token}"))
        .send()
        .await
        .unwrap()
        .json()
        .await
        .unwrap();
    assert_eq!(info["UserCanWrite"], json!(true), ".{extension}");

    let fetched = client
        .get(format!(
            "{base}/wopi/files/{file_id}/contents?access_token={token}"
        ))
        .send()
        .await
        .unwrap();
    assert_eq!(fetched.status(), reqwest::StatusCode::OK, ".{extension}");
    assert_eq!(
        fetched.bytes().await.unwrap().as_ref(),
        original_bytes.as_slice(),
        ".{extension}: GetFile must return the document byte-for-byte"
    );

    // --- lock, as a real editing session does ---
    let lock_value = format!("LOCK-{extension}");
    assert_eq!(
        client
            .post(format!("{base}/wopi/files/{file_id}?access_token={token}"))
            .header("X-WOPI-Override", "LOCK")
            .header("X-WOPI-Lock", &lock_value)
            .send()
            .await
            .unwrap()
            .status(),
        reqwest::StatusCode::OK,
        ".{extension}"
    );

    // --- modify: build a genuine replacement document in the SAME
    //     format (Task 11: no silent format conversion) ---
    let replacement_dir = tempfile::tempdir().unwrap();
    let replacement = make_fixture(
        replacement_dir.path(),
        "replacement",
        extension,
        kind,
        &modified_marker,
    )
    .await;
    let replacement_bytes = std::fs::read(&replacement).unwrap();

    // --- save through the real WOPI PutFile ---
    let put = client
        .post(format!(
            "{base}/wopi/files/{file_id}/contents?access_token={token}"
        ))
        .header("X-WOPI-Lock", &lock_value)
        .body(replacement_bytes.clone())
        .send()
        .await
        .unwrap();
    assert_eq!(
        put.status(),
        reqwest::StatusCode::OK,
        ".{extension}: PutFile failed"
    );

    // --- close the session ---
    assert_eq!(
        client
            .post(format!("{base}/wopi/files/{file_id}?access_token={token}"))
            .header("X-WOPI-Override", "UNLOCK")
            .header("X-WOPI-Lock", &lock_value)
            .send()
            .await
            .unwrap()
            .status(),
        reqwest::StatusCode::OK,
        ".{extension}"
    );

    // --- reopen and verify CONTENT, never the status code (Task 10) ---
    let reopened = client
        .get(format!(
            "{base}/wopi/files/{file_id}/contents?access_token={token}"
        ))
        .send()
        .await
        .unwrap();
    assert_eq!(reopened.status(), reqwest::StatusCode::OK, ".{extension}");
    let reopened_bytes = reopened.bytes().await.unwrap().to_vec();
    assert_eq!(
        reopened_bytes, replacement_bytes,
        ".{extension}: reopening must return exactly what was saved"
    );

    // The canonical on-disk file is a valid document of its ORIGINAL
    // format and contains the modification.
    let after = read_back(&doc, kind).await;
    assert!(
        after.contains(&modified_marker),
        ".{extension}: the saved document does not contain the modification \
         (got {after:?})"
    );
    assert!(
        !after.contains(&original_marker),
        ".{extension}: the original content survived a save that should have \
         replaced it (got {after:?})"
    );

    // Task 11: the file kept its own extension and is still recognised
    // as that format by LibreOffice (read_back above would have failed
    // outright otherwise), and the bytes on disk are the saved ones.
    assert_eq!(
        doc.extension().unwrap().to_string_lossy(),
        extension,
        ".{extension}: the saved file must keep its original extension"
    );
    assert_eq!(std::fs::read(&doc).unwrap(), replacement_bytes);
}

/// Task 9/10/11: every required format, end to end.
///
/// Runs as one test because each round trip drives several real
/// `LibreOffice` conversions; sharing one server and one workspace keeps
/// the whole matrix to a single setup while still asserting each format
/// independently.
#[tokio::test]
async fn task_9_10_11_all_required_formats_round_trip() {
    if !soffice_available().await {
        clouddesk_test_support::blocked_by_environment(
            "task_9_10_11_all_required_formats_round_trip",
            clouddesk_test_support::reason::CONTAINER_RUNTIME_UNAVAILABLE,
        );
        return;
    }
    let (base, dir, pool) = application().await;
    let admin = bootstrap_admin(&base).await;
    let user_id = create_user(&base, &admin, "formatuser").await;
    let workspace = tempfile::tempdir_in(dir.path()).unwrap();
    add_root(&base, &admin, &user_id, workspace.path()).await;

    for (extension, kind) in [
        // Modern ODF
        ("odt", Kind::Text),
        ("ods", Kind::Sheet),
        ("odp", Kind::Slides),
        // Modern OOXML
        ("docx", Kind::Text),
        ("xlsx", Kind::Sheet),
        ("pptx", Kind::Slides),
        // Genuine legacy binary formats (Task 11)
        ("doc", Kind::Text),
        ("xls", Kind::Sheet),
        ("ppt", Kind::Slides),
    ] {
        round_trip(&base, &pool, &user_id, workspace.path(), extension, kind).await;
        eprintln!("format round-trip PASS: .{extension}");
    }
}
