//! Live acceptance runner for CloudDesk-OS.
//!
//! CLAUDE-NIGHTMARE audit note: the previous version of this file hardcoded
//! `report.push_str("- X: **PASS**\n")` for its entire SSH, SFTP, and
//! cross-provider transfer-matrix sections without ever importing `russh` or
//! calling any SSH/SFTP code. This rewrite removes every unexecuted claim.
//! Every line in the generated report is produced from an actual `Result`
//! returned by calling the real product code
//! (`clouddesk_remote::{s3,webdav,ssh,sftp}`) against the real disposable
//! fixtures started by `docker compose up -d` in this directory
//! (`tests/acceptance/docker-compose.yml`). Nothing here is simulated.
//!
//! What this tool intentionally does NOT claim:
//! - Brave/Code/Office/FFmpeg: no backend implementation exists anywhere in
//!   this repository for any of these (see `V1_TRUE_CLOSURE.md`). Reporting
//!   these as "BLOCKED (no fixture)" would imply the feature exists and
//!   merely couldn't be exercised here; that would be as false as the
//!   previous hardcoded PASS lines. They are reported as
//!   `IMPLEMENTATION MISSING`.
//! - SSH agent forwarding, keyboard-interactive auth, ProxyJump, and SSH
//!   certificate validation: `crates/remote/src/ssh.rs` either `bail!`s
//!   (agent, keyboard-interactive) or silently ignores the certificate and
//!   falls back to plain key auth (`SshAuth::Certificate`). Reported
//!   accordingly, not exercised as if they worked.

use anyhow::{Context, Result};
use clouddesk_remote::ssh::{SshAuth, SshSession};
use clouddesk_remote::webdav::WebDavProvider;
use clouddesk_remote::{s3::S3Provider, sftp::SftpProvider};
use clouddesk_vfs::VfsProvider;
use std::fmt::Write as _;
use std::time::Duration;

struct Report {
    text: String,
}

impl Report {
    fn new() -> Self {
        Self {
            text: String::from(
                "# CloudDesk-OS Live Acceptance Report\n\n\
Generated by executing the real product code (`clouddesk-remote`) against \
real disposable fixtures (`tests/acceptance/docker-compose.yml`). Every \
line below reflects an actual `Result` from a real call; nothing is \
hardcoded.\n\n",
            ),
        }
    }

    fn section(&mut self, name: &str) {
        let _ = writeln!(self.text, "## {name}\n");
    }

    fn record<T>(&mut self, name: &str, result: &Result<T>) {
        match result {
            Ok(_) => {
                let _ = writeln!(self.text, "- {name}: **PASS** (executed, succeeded)");
            }
            Err(e) => {
                let _ = writeln!(self.text, "- {name}: **FAIL** — `{e}`");
            }
        }
    }

    fn record_bool(&mut self, name: &str, condition_met: bool, detail: &str) {
        if condition_met {
            let _ = writeln!(self.text, "- {name}: **PASS** ({detail})");
        } else {
            let _ = writeln!(self.text, "- {name}: **FAIL** ({detail})");
        }
    }

    fn missing(&mut self, name: &str, reason: &str) {
        let _ = writeln!(self.text, "- {name}: **IMPLEMENTATION MISSING** — {reason}");
    }

    fn not_executed(&mut self, name: &str, reason: &str) {
        let _ = writeln!(self.text, "- {name}: **NOT EXECUTED** — {reason}");
    }

    fn blank(&mut self) {
        self.text.push('\n');
    }
}

#[tokio::main]
async fn main() -> Result<()> {
    tracing_subscriber::fmt::init();
    let mut report = Report::new();

    run_s3(&mut report).await;
    run_webdav(&mut report).await;
    let (real_host_key, wrong_host_key) = run_ssh(&mut report).await?;
    run_sftp(&mut report, &real_host_key).await;
    run_ssh_key_auth(&mut report).await;
    run_ssh_host_key_rejection(&mut report, &real_host_key, &wrong_host_key).await;
    run_unimplemented_ssh_surface(&mut report);
    run_missing_applications(&mut report);

    report.section("Conclusion");
    report.text.push_str(
        "This report only ever reflects executed live checks against real \
disposable fixtures. It does not cover process-level UI flows, backup/\
restore, or the full v1.0 requirement set — see `RELEASE_EVIDENCE_AUDIT.md` \
and `V1_TRUE_CLOSURE.md` for the complete picture.\n",
    );

    std::fs::write("LIVE_ACCEPTANCE_REPORT.md", &report.text)
        .context("failed to write LIVE_ACCEPTANCE_REPORT.md")?;
    println!("{}", report.text);
    println!("Acceptance run complete. Report written to LIVE_ACCEPTANCE_REPORT.md");
    Ok(())
}

async fn run_s3(report: &mut Report) {
    report.section("Real MinIO/S3 (clouddesk_remote::s3::S3Provider)");

    std::env::set_var("AWS_ACCESS_KEY_ID", "admin");
    std::env::set_var("AWS_SECRET_ACCESS_KEY", "password123");
    let config = aws_config::defaults(aws_config::BehaviorVersion::latest())
        .endpoint_url("http://127.0.0.1:9000")
        .region(aws_sdk_s3::config::Region::new("us-east-1"))
        .load()
        .await;

    // Ensure the bucket exists (disposable fixture state is not guaranteed
    // to survive across runs of this tool).
    let sdk_conf = aws_sdk_s3::config::Builder::from(&config)
        .force_path_style(true)
        .build();
    let raw_client = aws_sdk_s3::Client::from_conf(sdk_conf);
    let _ = raw_client
        .create_bucket()
        .bucket("acceptance-bucket")
        .send()
        .await;

    let handle = tokio::runtime::Handle::current();
    let s3 = S3Provider::new(&config, "acceptance-bucket".to_string(), handle.clone());

    let data = b"hello product-code s3".to_vec();
    let write_result = s3
        .write_file("/acceptance.txt", &data)
        .map_err(anyhow::Error::from);
    report.record("upload (new key)", &write_result);

    let list_result = s3.list("/").map_err(anyhow::Error::from);
    let listed_ok = list_result
        .as_ref()
        .map(|entries| entries.iter().any(|e| e.name == "acceptance.txt"))
        .unwrap_or(false);
    report.record_bool(
        "object listing",
        listed_ok,
        "acceptance.txt present in ListObjectsV2 result",
    );

    let read_back = s3
        .read_limited("/acceptance.txt", data.len())
        .map_err(anyhow::Error::from);
    let matches = read_back.as_ref().map(|d| *d == data).unwrap_or(false);
    report.record_bool(
        "download / round-trip",
        matches,
        "bytes read back match bytes written",
    );

    let big = vec![0x5A_u8; 6 * 1024 * 1024];
    let multipart_write = s3
        .write_file("/acceptance-big.bin", &big)
        .map_err(anyhow::Error::from);
    report.record("multipart upload >5 MB", &multipart_write);
    let multipart_read = s3
        .read_limited("/acceptance-big.bin", big.len())
        .map_err(anyhow::Error::from);
    let multipart_matches = multipart_read.as_ref().map(|d| *d == big).unwrap_or(false);
    report.record_bool(
        "multipart round-trip",
        multipart_matches,
        "6 MB payload read back byte-for-byte",
    );

    let delete_result = s3.trash("/acceptance.txt").map_err(anyhow::Error::from);
    report.record("delete", &delete_result);
    let _ = s3.trash("/acceptance-big.bin");

    let bad_creds_config = aws_config::defaults(aws_config::BehaviorVersion::latest())
        .endpoint_url("http://127.0.0.1:9000")
        .region(aws_sdk_s3::config::Region::new("us-east-1"))
        .credentials_provider(aws_sdk_s3::config::Credentials::new(
            "wrong", "wrong", None, None, "static",
        ))
        .load()
        .await;
    let bad_s3 = S3Provider::new(&bad_creds_config, "acceptance-bucket".to_string(), handle);
    let bad_write = bad_s3.write_file("/should-fail.txt", b"x");
    report.record_bool(
        "invalid credentials rejected",
        bad_write.is_err(),
        "write with wrong credentials returned an error",
    );
    report.blank();
}

async fn run_webdav(report: &mut Report) {
    report.section("Real WebDAV server (clouddesk_remote::webdav::WebDavProvider)");
    let handle = tokio::runtime::Handle::current();
    let provider = WebDavProvider::new(
        "http://127.0.0.1:8080".to_string(),
        Some("testuser".to_string()),
        Some("testpassword".to_string()),
        handle.clone(),
    );

    let data = b"hello product-code webdav".to_vec();
    let put_result = provider
        .write_file("/acceptance.txt", &data)
        .map_err(anyhow::Error::from);
    report.record("PUT (new file)", &put_result);

    let list_result = provider.list("/").map_err(anyhow::Error::from);
    let browsed_ok = list_result
        .as_ref()
        .map(|entries| entries.iter().any(|e| e.name == "acceptance.txt"))
        .unwrap_or(false);
    report.record_bool(
        "browse (PROPFIND)",
        browsed_ok,
        "acceptance.txt present in listing",
    );

    let get_result = provider
        .read_limited("/acceptance.txt", data.len())
        .map_err(anyhow::Error::from);
    let get_matches = get_result.as_ref().map(|d| *d == data).unwrap_or(false);
    report.record_bool("GET", get_matches, "bytes read back match bytes written");

    let mkcol_result = provider
        .create_directory("/acceptance-dir")
        .map_err(anyhow::Error::from);
    report.record("MKCOL", &mkcol_result);

    let move_result = provider
        .rename("/acceptance.txt", "/acceptance-dir/moved.txt")
        .map_err(anyhow::Error::from);
    report.record("MOVE", &move_result);

    let delete_result = provider
        .trash("/acceptance-dir/moved.txt")
        .map_err(anyhow::Error::from);
    report.record("DELETE", &delete_result);

    let bad_provider = WebDavProvider::new(
        "http://127.0.0.1:8080".to_string(),
        Some("testuser".to_string()),
        Some("wrong-password".to_string()),
        handle,
    );
    let bad_write = bad_provider.write_file("/should-fail.txt", b"x");
    report.record_bool(
        "wrong credentials rejected",
        bad_write.is_err(),
        "PUT with wrong password returned an error",
    );
    report.blank();
}

/// Returns `(real_host_key_base64, unrelated_key_base64)` for reuse by the
/// SFTP and host-key-rejection sections.
async fn run_ssh(report: &mut Report) -> Result<(String, String)> {
    report.section("Real OpenSSH server (clouddesk_remote::ssh::SshSession)");

    let real_host_key = scan_host_key("127.0.0.1", 2222)
        .await
        .context("ssh-keyscan against the disposable OpenSSH fixture")?;

    let password_auth = SshSession::connect(
        "127.0.0.1",
        2222,
        "testuser",
        SshAuth::Password("testpassword".into()),
        Duration::from_secs(5),
    )
    .await
    .map(|_| ());

    report.record("password auth", &password_auth);

    let wrong_password = SshSession::connect(
        "127.0.0.1",
        2222,
        "testuser",
        SshAuth::Password("definitely-wrong".into()),
        Duration::from_secs(5),
    )
    .await;
    report.record_bool(
        "wrong password rejected",
        wrong_password.is_err(),
        "authentication with an incorrect password returned an error",
    );
    report.blank();

    // Not a real host key — used to prove mismatch rejection later.
    let unrelated_key = base64_of([9_u8; 32]);
    Ok((real_host_key, unrelated_key))
}

async fn run_ssh_key_auth(report: &mut Report) {
    report.section("SSH key-based authentication");
    let rsa_key = std::fs::read_to_string("/tmp/claude-1000/sshkeys/rsa_key");
    let encrypted_key = std::fs::read_to_string("/tmp/claude-1000/sshkeys/encrypted_key");

    match rsa_key {
        Ok(key_data) => {
            let result = SshSession::connect(
                "127.0.0.1",
                2222,
                "testuser",
                SshAuth::PrivateKey {
                    key_data,
                    passphrase: None,
                },
                Duration::from_secs(5),
            )
            .await
            .map(|_| ());
            report.record("RSA private key auth", &result);
        }
        Err(_) => report.not_executed(
            "RSA private key auth",
            "no RSA key was provisioned into the fixture's authorized_keys for this run",
        ),
    }

    match encrypted_key {
        Ok(key_data) => {
            let result = SshSession::connect(
                "127.0.0.1",
                2222,
                "testuser",
                SshAuth::PrivateKey {
                    key_data,
                    passphrase: Some("testpass123".to_string()),
                },
                Duration::from_secs(5),
            )
            .await
            .map(|_| ());
            report.record("encrypted private key + passphrase auth", &result);
        }
        Err(_) => report.not_executed(
            "encrypted private key + passphrase auth",
            "no passphrase-protected key was provisioned into the fixture for this run",
        ),
    }
    report.blank();
}

async fn run_ssh_host_key_rejection(report: &mut Report, real_key: &str, wrong_key: &str) {
    report.section("SSH host-key verification (CLAUDE-NIGHTMARE-002 regression)");

    let pinned_to_real = SshSession::connect_pinned(
        "127.0.0.1",
        2222,
        "testuser",
        SshAuth::Password("testpassword".into()),
        Duration::from_secs(5),
        Some(real_key.to_string()),
    )
    .await
    .map(|_| ());

    report.record(
        "connection pinned to the real host key succeeds",
        &pinned_to_real,
    );

    let pinned_to_wrong = SshSession::connect_pinned(
        "127.0.0.1",
        2222,
        "testuser",
        SshAuth::Password("testpassword".into()),
        Duration::from_secs(5),
        Some(wrong_key.to_string()),
    )
    .await;
    report.record_bool(
        "connection pinned to a replaced/wrong host key is rejected",
        pinned_to_wrong.is_err(),
        "simulated host-key replacement / MITM was refused, not silently accepted",
    );
    report.blank();
}

async fn run_sftp(report: &mut Report, real_host_key: &str) {
    report.section(
        "Real SFTP server (clouddesk_remote::sftp::SftpProvider — CLAUDE-NIGHTMARE-003/-004 regressions)",
    );

    let session = SshSession::connect_pinned(
        "127.0.0.1",
        2222,
        "testuser",
        SshAuth::Password("testpassword".into()),
        Duration::from_secs(5),
        Some(real_host_key.to_string()),
    )
    .await;
    let mut session = match session {
        Ok(session) => session,
        Err(error) => {
            report.record::<()>("SSH connection for SFTP", &Err(error));
            report.blank();
            return;
        }
    };

    let sftp = match session.open_sftp_session().await {
        Ok(sftp) => sftp,
        Err(error) => {
            report.record::<()>("open SFTP subsystem", &Err(error));
            report.blank();
            return;
        }
    };
    let handle = tokio::runtime::Handle::current();
    let provider = SftpProvider::new(sftp, handle);

    // CLAUDE-NIGHTMARE-004: this must succeed against the real,
    // non-chrooted fixture (it used to fail with "No such file").
    let list_result = provider.list("/").map_err(anyhow::Error::from);
    report.record("list (root)", &list_result);

    // CLAUDE-NIGHTMARE-003: uploading a file that has never existed on the
    // remote must succeed (it used to fail with "No such file").
    let content = b"acceptance sftp upload, never existed before".to_vec();
    let upload_result = provider
        .write_file("/acceptance-sftp.bin", &content)
        .map_err(anyhow::Error::from);
    report.record("upload (new file)", &upload_result);

    let download_result = provider
        .read_limited("/acceptance-sftp.bin", content.len())
        .map_err(anyhow::Error::from);
    let download_matches = download_result
        .as_ref()
        .map(|d| *d == content)
        .unwrap_or(false);
    report.record_bool(
        "download / round-trip",
        download_matches,
        "bytes match what was uploaded",
    );

    let mkdir_result = provider
        .create_directory("/acceptance-sftp-dir")
        .map_err(anyhow::Error::from);
    report.record("mkdir", &mkdir_result);

    let rename_result = provider
        .rename("/acceptance-sftp.bin", "/acceptance-sftp-dir/renamed.bin")
        .map_err(anyhow::Error::from);
    report.record("rename", &rename_result);

    let delete_result = provider
        .trash("/acceptance-sftp-dir/renamed.bin")
        .map_err(anyhow::Error::from);
    report.record("delete", &delete_result);

    let large = vec![0x33_u8; 4 * 1024 * 1024];
    let large_upload = provider
        .write_file("/acceptance-large.bin", &large)
        .map_err(anyhow::Error::from);
    report.record("large streamed file (4 MB) upload", &large_upload);
    let large_download = provider
        .read_limited("/acceptance-large.bin", large.len())
        .map_err(anyhow::Error::from);
    let large_matches = large_download
        .as_ref()
        .map(|d| *d == large)
        .unwrap_or(false);
    report.record_bool(
        "large streamed file round-trip",
        large_matches,
        "4 MB payload matches byte-for-byte",
    );
    let _ = provider.trash("/acceptance-large.bin");

    report.blank();
}

fn run_unimplemented_ssh_surface(report: &mut Report) {
    report.section("SSH authentication surface with no implementation");
    report.missing(
        "SSH agent forwarding",
        "SshAuth::Agent immediately returns an error \
(\"Agent auth not fully implemented via sockets yet\") in crates/remote/src/ssh.rs — \
no socket-forwarding code exists",
    );
    report.missing(
        "keyboard-interactive authentication",
        "SshAuth::KeyboardInteractive immediately returns an error \
(\"Keyboard interactive auth not implemented in russh 0.62\") — no interactive \
prompt/response handling exists",
    );
    report.missing(
        "SSH certificate authentication",
        "SshAuth::Certificate decodes only key_data and silently ignores cert_data — \
no OpenSSH certificate parsing or validation exists; this is a facade, not an \
implementation",
    );
    report.not_executed(
        "ProxyJump / bastion hosts",
        "SshSession::connect_proxyjump exists and is used by the new host-key-pinning \
regression tests, but has zero callers anywhere in services/clouddeskd — no HTTP \
endpoint or transfer path ever constructs a ProxyJump connection, so there is no \
product surface to exercise here",
    );
    report.blank();
}

fn run_missing_applications(report: &mut Report) {
    report.section("Applications with no backend implementation");
    for (name, reason) in [
        (
            "FFmpeg probing / remux / transcoding",
            "no reference to ffmpeg exists anywhere in the Rust codebase (grep -r ffmpeg \
over every *.rs file is empty); stream_media/preview_media are plain HTTP byte-range \
file serving with no transcoding",
        ),
        (
            "Video player application",
            "no Video app component exists in apps/web/src/lib; GalleryApp.svelte has \
no video-related code",
        ),
        (
            "Music application",
            "no Music app, playlist, or ID3-metadata code exists anywhere in the \
repository (Rust or Svelte)",
        ),
        (
            "Office editing runtime (LibreOffice/Collabora/WOPI)",
            "crates/runtime is a JSON manifest schema/validator only; \
RuntimeDependency::Office is an enum variant with no launcher, container \
orchestration, or WOPI implementation behind it; no OfficeApp component exists",
        ),
        (
            "VS Code-compatible runtime",
            "same manifest-only pattern as Office; RuntimeDependency::Code is an enum \
variant with no code-server process/container launcher; no CodeApp component exists",
        ),
        (
            "Brave remote-browser runtime",
            "same manifest-only pattern; RuntimeDependency::Browser is an enum variant \
with no KasmVNC/Brave container launcher; no BrowserApp component exists",
        ),
        (
            "Archive create/extract",
            "no zip/tar handling exists anywhere in the Rust codebase",
        ),
        (
            "ACL viewing/editing",
            "ProviderFeature::Acl is declared as a capability flag but never backed by \
getfacl/setfacl or any ACL library call",
        ),
        (
            "Resumable/chunked upload",
            "ProviderFeature::ResumableUpload is declared as a capability flag with no \
chunked-upload-session protocol behind it",
        ),
        (
            "SCP transfers",
            "GOAL.md G9 requires SCP \"where appropriate\"; no scp-specific code exists \
(only SFTP)",
        ),
    ] {
        report.missing(name, reason);
    }
    report.blank();
}

async fn scan_host_key(host: &str, port: u16) -> Result<String> {
    let output = tokio::process::Command::new("ssh-keyscan")
        .args(["-t", "ed25519", "-p", &port.to_string(), host])
        .output()
        .await
        .context("failed to run ssh-keyscan")?;
    let stdout = String::from_utf8_lossy(&output.stdout);
    let key_field = stdout
        .lines()
        .find(|line| !line.starts_with('#'))
        .and_then(|line| line.split_whitespace().nth(2))
        .context("ssh-keyscan produced no usable host key line")?;
    Ok(key_field.to_string())
}

fn base64_of(bytes: [u8; 32]) -> String {
    use base64::Engine;
    base64::engine::general_purpose::STANDARD.encode(bytes)
}
