[package]
name = "clouddesk-vfs"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cap-std.workspace = true
flate2 = "1"
serde.workspace = true
tar = "0.4.46"
thiserror.workspace = true
zip = "8.6.0"

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
